### ISSUE TITLE
viewportZoom: Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by sfranzyshen** [Aricwithana/LCARS-SDK#10]
I'm trying to implement viewportZoom. I'm using the example give on the wiki ... but i get the error ...
`Uncaught TypeError: Cannot read property 'css' of undefined at Object.viewportZoom`
here is the code where it's being setup ... in my module.js file
```
{type:'wrapper', id:'wpr_viewport', version:'row', flex:'h', 
	arrive:function(){LCARS.helper.viewportZoom(this.dom, {width:1440, height:1080}); 
		window.addEventListener("resize", function(){LCARS.helper.viewportZoom(this.dom, {width:1440, height:1080});});},

	children:[
```
and the line(s) in the sdk ...
```
        viewportZoom:function(object, oArgs){
.......
            object.css('zoom', zoomLevel);
```
the error(s) only occur during the resize eventListener call ... it works fine when called from the arrive call ... seems this.dom behaves differently depending on who calls it ... a promise or event ...

**Comment by sfranzyshen** [comment]
full code example ...
https://github.com/sfranzyshen/LCARS-SDK-ARCHIVE/blob/gh-pages/19182.4/interfaces/color-generator/module.js

**Comment by Aricwithana** [comment]
Ah, looks like a 'this' issue since the call is within a parent function.  It has to be set via variable instead.

I've updated the wiki to account for it.

<pre><code>
        arrive:function(){
            var dom = this.dom;
            LCARS.helper.viewportZoom(dom, {width:1440, height:1080});
            window.addEventListener("resize", function(){
                LCARS.helper.viewportZoom(dom, {width:1440, height:1080}); 
            });
        }

</code></pre>

**Comment by sfranzyshen** [comment]
Once again Brilliant! that did it ;)
