### ISSUE TITLE
Which version of Illustrator do you use?

### ISSUE THREAD

**Issue by sg-x** [Aricwithana/LCARS-SDK#2]
Hi,
I've seen that you are using Adobe Illustrator files for mockup and CSS extraction. 
Which version are you using, cause CS2 says it was made with an higher version?

Thanks,

sg-x

**Comment by Aricwithana** [comment]
I currently use the most current version of Illustrator because I have to have it for work.  Is there another format you would suggest?  I could just save out as an non-flat PDF but then one loses all the guides but that isn't that terrible to replace.

**Comment by sg-x** [comment]
Cause I'm not the "graphical" guy, my only suggestion would be InkScape it's a free software for SVG editing. It's not that complex than Illustrator but maybe it lasts for this usecase. Maybe it is also possible to export it to an CS2 compatible format.

Do you know another way to get the CSS?

As a last thing I want to thank you for your awesome work, it really makes fun to work with the SDK.

sg-x

**Comment by Aricwithana** [comment]
http://lcarssdk.org/upload/lcarssdk_vectorTemplate_cs2.ai

Give that a try!  My next update to the SDK will include a few different version of the vector file.

Glad you are enjoying the project.  It isn't perfect, not by a long shot, but it gets the job done!  What are your coding specializations?  The LCARS-NV project will be needing more human power here in the near future.

**Comment by Aricwithana** [comment]
Removed al the old ones and just keep the the recent illustrator files and an editable pdf file.
