### ISSUE TITLE
visual-guide uses serifed fonts in Firefox 49 on Ubuntu 16.04

### ISSUE THREAD

**Issue by tenleftfingers** [Aricwithana/LCARS-SDK#3]
This is what I get from the latest release:

Should there be a font bundled with the release & referenced in the CSS?

![screenshot from 2016-10-05 04-58-13](https://cloud.githubusercontent.com/assets/1757768/19100638/8e1e6068-8ab8-11e6-8bcc-af0c1353cc7b.png)

**Comment by Aricwithana** [comment]
That is the security policy on firefox.  You can change the security.fileuri.strict_origin_policy to false in about:config but then your filesystem is exposed so use with caution.
