### ISSUE TITLE
Case-Sensitivity in visual-guide demo

### ISSUE THREAD

**Issue by Digicrat** [Aricwithana/LCARS-SDK#5]
Some servers, such as Apache on Linux, are case-sensitive by default.  In the interfaces/visual-guide/index.html both the directory and filename "scrollButton" is used, while the actual file and directory is "scrollbutton."  Either rename the file & directory, or change the case in the index.html (what I just did).

Btw, nice looking library. I'm contemplating setting it up with my home automation system.  

Also, just in case you haven't already noticed, your main site (lcarssdk.org) is currently offline.  It crashed somewhere around 6 or 7PM EST from what I can tell (I was looking at your Voyager demo one minute, and an error message the next).

**Comment by Aricwithana** [comment]
Thanks for the kind words!  Ah yea, silly american cards got updated so my auto pay didn't go through since I didn't update the info.  The website is back up and running!

Sure, I'll go through and fix up any of the file names there and push out a small update.

**Comment by Aricwithana** [comment]
Should be in place!
