### ISSUE TITLE
Archive (ver 3.xx) Section on the Wiki

### ISSUE THREAD

**Issue by sfranzyshen** [Aricwithana/LCARS-SDK#7]
any objections to creating a archived section on the wiki? to document the older versions (3.xx)? 
I'm willing to collect the old pages and assemble them into a single page that could be added to the wiki?

**Comment by Aricwithana** [comment]
Ah I didn't think about archiving them, I already deleted most of it as I fill it up with the newer.

**Comment by sfranzyshen** [comment]
> Ah I didn't think about archiving them, I already deleted most of it as I fill it up with the newer.

it's ok ... they are archived threw the git history ... i'll pull each one and rebuild the md file (i'll put them all under one file) and i think i can add it up to the wiki ... i'll try

**Comment by sfranzyshen** [comment]
Hope I didn't miss anything ...

**Comment by Aricwithana** [comment]
Looks good there.  Thanks a bunch there!  The new wiki is almost done here too.
